-- Vehicle Lease database seed

-- Categories
INSERT INTO categories (slug, name, description) VALUES ('budget-friendly', 'Budget Friendly', 'Affordable lease deals under £300/month');
INSERT INTO categories (slug, name, description) VALUES ('family-cars', 'Family Cars', 'Spacious vehicles for families');
INSERT INTO categories (slug, name, description) VALUES ('city-cars', 'City Cars', 'Compact cars perfect for urban driving');
INSERT INTO categories (slug, name, description) VALUES ('suvs', 'SUVs', 'Sport Utility Vehicles with raised seating');
INSERT INTO categories (slug, name, description) VALUES ('saloons', 'Saloons', 'Executive saloon cars');
INSERT INTO categories (slug, name, description) VALUES ('electric', 'Electric', 'Zero-emission electric vehicles');
INSERT INTO categories (slug, name, description) VALUES ('hybrid', 'Hybrid', 'Fuel-efficient hybrid vehicles');
INSERT INTO categories (slug, name, description) VALUES ('premium', 'Premium', 'Luxury and premium brand vehicles');

-- Vehicles
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-fiesta-2024', 'Ford', 'Fiesta', 2024, 'Hatchback', 'Manual', 'Petrol', 1100, 85, 115, 52, 5, 5, 311, NULL, NULL, NULL, NULL, 'Compact city car with excellent fuel economy', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-fiesta-2024', 'Ford', 'Fiesta', 2024, 'Hatchback', 'Automatic', 'Petrol', 1200, 100, 125, 47, 5, 5, 311, NULL, NULL, NULL, NULL, 'Automatic city car for easy urban commuting', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-focus-2024', 'Ford', 'Focus', 2024, 'Hatchback', 'Manual', 'Petrol', 1500, 125, 135, 45, 5, 5, 356, NULL, NULL, NULL, NULL, 'Best-selling family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-focus-2024', 'Ford', 'Focus', 2024, 'Hatchback', 'Automatic', 'Hybrid', 1500, 155, 105, 55, 5, 5, 356, NULL, NULL, NULL, NULL, 'Efficient hybrid family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-mondeo-2024', 'Ford', 'Mondeo', 2024, 'Saloon', 'Automatic', 'Hybrid', 1500, 187, 95, 62, 5, 4, 525, NULL, NULL, NULL, NULL, 'Executive hybrid saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-kuga-2024', 'Ford', 'Kuga', 2024, 'SUV', 'Manual', 'Petrol', 1500, 154, 125, 48, 5, 5, 456, NULL, NULL, NULL, NULL, 'Compact SUV with efficient petrol engine', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-kuga-2024', 'Ford', 'Kuga', 2024, 'SUV', 'Automatic', 'Hybrid', 1500, 187, 105, 55, 5, 5, 456, NULL, NULL, NULL, NULL, 'Mid-size SUV with hybrid efficiency', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-puma-2024', 'Ford', 'Puma', 2024, 'SUV', 'Automatic', 'Hybrid', 1200, 155, 110, 52, 5, 5, 383, NULL, NULL, NULL, NULL, 'Compact trendy SUV with hybrid power', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-s-max-2024', 'Ford', 'S-Max', 2024, 'MPV', 'Automatic', 'Petrol', 2000, 200, 155, 38, 7, 5, 565, NULL, NULL, NULL, NULL, 'Premium 7-seat family MPV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('ford-mustang-mach-e-2024', 'Ford', 'Mustang Mach-E', 2024, 'SUV', 'Automatic', 'Electric', NULL, 290, NULL, 110, 5, 5, 486, NULL, NULL, NULL, NULL, 'Performance electric SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('vauxhall-corsa-2024', 'Vauxhall', 'Corsa', 2024, 'Hatchback', 'Manual', 'Petrol', 1200, 100, 128, 46, 5, 5, 309, NULL, NULL, NULL, NULL, 'Stylish city car with modern tech', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('vauxhall-corsa-2024', 'Vauxhall', 'Corsa', 2024, 'Hatchback', 'Automatic', 'Electric', NULL, 156, NULL, 95, 5, 5, 309, NULL, NULL, NULL, NULL, 'All-electric city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('vauxhall-astra-2024', 'Vauxhall', 'Astra', 2024, 'Hatchback', 'Manual', 'Petrol', 1400, 130, 135, 44, 5, 5, 370, NULL, NULL, NULL, NULL, 'Practical family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('vauxhall-astra-2024', 'Vauxhall', 'Astra', 2024, 'Hatchback', 'Automatic', 'Petrol', 1600, 170, 155, 38, 5, 5, 370, NULL, NULL, NULL, NULL, 'Sportier Astra with petrol power', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('vauxhall-grandland-2024', 'Vauxhall', 'Grandland', 2024, 'SUV', 'Automatic', 'Petrol', 1200, 130, 135, 44, 5, 5, 550, NULL, NULL, NULL, NULL, 'Compact SUV with premium feel', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('vauxhall-mokka-2024', 'Vauxhall', 'Mokka', 2024, 'SUV', 'Automatic', 'Electric', NULL, 156, NULL, 95, 5, 5, 469, NULL, NULL, NULL, NULL, 'Electric compact crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-1-series-2024', 'BMW', '1 Series', 2024, 'Hatchback', 'Automatic', 'Petrol', 1500, 140, 145, 41, 5, 5, 345, NULL, NULL, NULL, NULL, 'Premium entry-level hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-2-series-2024', 'BMW', '2 Series', 2024, 'Coupe', 'Automatic', 'Petrol', 1998, 255, 165, 35, 4, 2, 390, NULL, NULL, NULL, NULL, 'Sporty premium coupe', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-3-series-2024', 'BMW', '3 Series', 2024, 'Saloon', 'Automatic', 'Petrol', 1998, 255, 155, 38, 5, 4, 460, NULL, NULL, NULL, NULL, 'Premium executive saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-3-series-2024', 'BMW', '3 Series', 2024, 'Saloon', 'Automatic', 'Hybrid', 1500, 288, 115, 50, 5, 4, 460, NULL, NULL, NULL, NULL, 'Efficient hybrid saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-5-series-2024', 'BMW', '5 Series', 2024, 'Saloon', 'Automatic', 'Petrol', 2998, 335, 175, 34, 5, 4, 530, NULL, NULL, NULL, NULL, 'Luxury executive saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-x1-2024', 'BMW', 'X1', 2024, 'SUV', 'Automatic', 'Petrol', 1500, 140, 150, 40, 5, 5, 540, NULL, NULL, NULL, NULL, 'Compact premium SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-x3-2024', 'BMW', 'X3', 2024, 'SUV', 'Automatic', 'Petrol', 1998, 255, 175, 34, 5, 5, 553, NULL, NULL, NULL, NULL, 'Premium compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-x5-2024', 'BMW', 'X5', 2024, 'SUV', 'Automatic', 'Petrol', 2998, 335, 195, 32, 7, 5, 645, NULL, NULL, NULL, NULL, 'Luxury 7-seat SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('bmw-i4-2024', 'BMW', 'i4', 2024, 'Saloon', 'Automatic', 'Electric', NULL, 335, NULL, 120, 5, 4, 495, NULL, NULL, NULL, NULL, 'Premium electric saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mercedes-benz-a-class-2024', 'Mercedes-Benz', 'A-Class', 2024, 'Hatchback', 'Automatic', 'Petrol', 1399, 136, 145, 41, 5, 5, 370, NULL, NULL, NULL, NULL, 'Premium compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mercedes-benz-c-class-2024', 'Mercedes-Benz', 'C-Class', 2024, 'Saloon', 'Automatic', 'Petrol', 1599, 204, 155, 39, 5, 4, 455, NULL, NULL, NULL, NULL, 'Luxury compact saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mercedes-benz-c-class-2024', 'Mercedes-Benz', 'C-Class', 2024, 'Saloon', 'Automatic', 'Hybrid', 1599, 259, 115, 52, 5, 4, 455, NULL, NULL, NULL, NULL, 'Efficient hybrid saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mercedes-benz-e-class-2024', 'Mercedes-Benz', 'E-Class', 2024, 'Saloon', 'Automatic', 'Petrol', 1991, 258, 165, 36, 5, 4, 540, NULL, NULL, NULL, NULL, 'Executive luxury saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mercedes-benz-gla-2024', 'Mercedes-Benz', 'GLA', 2024, 'SUV', 'Automatic', 'Petrol', 1399, 136, 150, 40, 5, 5, 435, NULL, NULL, NULL, NULL, 'Premium compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mercedes-benz-glc-2024', 'Mercedes-Benz', 'GLC', 2024, 'SUV', 'Automatic', 'Petrol', 1991, 258, 175, 34, 5, 5, 550, NULL, NULL, NULL, NULL, 'Premium mid-size SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('audi-a1-2024', 'Audi', 'A1', 2024, 'Hatchback', 'Automatic', 'Petrol', 1000, 110, 130, 46, 5, 5, 335, NULL, NULL, NULL, NULL, 'Premium city hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('audi-a3-2024', 'Audi', 'A3', 2024, 'Hatchback', 'Automatic', 'Petrol', 1498, 150, 145, 41, 5, 5, 380, NULL, NULL, NULL, NULL, 'Premium family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('audi-a4-2024', 'Audi', 'A4', 2024, 'Saloon', 'Automatic', 'Petrol', 1984, 204, 155, 39, 5, 4, 460, NULL, NULL, NULL, NULL, 'Premium executive saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('audi-q2-2024', 'Audi', 'Q2', 2024, 'SUV', 'Automatic', 'Petrol', 1498, 150, 150, 40, 5, 5, 405, NULL, NULL, NULL, NULL, 'Premium compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('audi-q3-2024', 'Audi', 'Q3', 2024, 'SUV', 'Automatic', 'Petrol', 1984, 204, 165, 37, 5, 5, 470, NULL, NULL, NULL, NULL, 'Premium mid-size SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('nissan-micra-2024', 'Nissan', 'Micra', 2024, 'Hatchback', 'Manual', 'Petrol', 1000, 71, 120, 50, 5, 5, 298, NULL, NULL, NULL, NULL, 'Reliable compact city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('nissan-qashqai-2024', 'Nissan', 'Qashqai', 2024, 'SUV', 'Manual', 'Petrol', 1600, 158, 145, 42, 5, 5, 430, NULL, NULL, NULL, NULL, 'Popular compact crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('nissan-qashqai-2024', 'Nissan', 'Qashqai', 2024, 'SUV', 'Automatic', 'Hybrid', 1597, 188, 115, 52, 5, 5, 430, NULL, NULL, NULL, NULL, 'Efficient hybrid crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('nissan-juke-2024', 'Nissan', 'Juke', 2024, 'SUV', 'Automatic', 'Petrol', 1200, 117, 135, 44, 5, 5, 422, NULL, NULL, NULL, NULL, 'Compact funky SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('nissan-leaf-2024', 'Nissan', 'Leaf', 2024, 'Hatchback', 'Automatic', 'Electric', NULL, 147, NULL, 102, 5, 5, 391, NULL, NULL, NULL, NULL, 'Best-selling electric hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('hyundai-i10-2024', 'Hyundai', 'i10', 2024, 'Hatchback', 'Manual', 'Petrol', 1197, 83, 120, 50, 5, 5, 252, NULL, NULL, NULL, NULL, 'Budget-friendly city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('hyundai-i20-2024', 'Hyundai', 'i20', 2024, 'Hatchback', 'Manual', 'Petrol', 1197, 99, 125, 47, 5, 5, 311, NULL, NULL, NULL, NULL, 'Value-for-money compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('hyundai-i30-2024', 'Hyundai', 'i30', 2024, 'Hatchback', 'Manual', 'Petrol', 1500, 120, 135, 44, 5, 5, 395, NULL, NULL, NULL, NULL, 'Practical family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('hyundai-tucson-2024', 'Hyundai', 'Tucson', 2024, 'SUV', 'Automatic', 'Petrol', 1599, 180, 150, 39, 5, 5, 620, NULL, NULL, NULL, NULL, 'Spacious mid-size SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('hyundai-kona-2024', 'Hyundai', 'Kona', 2024, 'SUV', 'Automatic', 'Electric', NULL, 204, NULL, 105, 5, 5, 406, NULL, NULL, NULL, NULL, 'Electric compact SUV with range', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('kia-picanto-2024', 'Kia', 'Picanto', 2024, 'Hatchback', 'Manual', 'Petrol', 1197, 83, 120, 50, 5, 5, 255, NULL, NULL, NULL, NULL, 'Budget city car with great warranty', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('kia-rio-2024', 'Kia', 'Rio', 2024, 'Hatchback', 'Manual', 'Petrol', 1197, 99, 125, 47, 5, 5, 311, NULL, NULL, NULL, NULL, 'Reliable compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('kia-ceed-2024', 'Kia', 'Ceed', 2024, 'Hatchback', 'Manual', 'Petrol', 1500, 120, 135, 44, 5, 5, 395, NULL, NULL, NULL, NULL, 'Well-equipped family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('kia-sportage-2024', 'Kia', 'Sportage', 2024, 'SUV', 'Automatic', 'Petrol', 1599, 180, 150, 39, 5, 5, 591, NULL, NULL, NULL, NULL, 'Stylish compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('kia-ev6-2024', 'Kia', 'EV6', 2024, 'Crossover', 'Automatic', 'Electric', NULL, 314, NULL, 120, 5, 5, 520, NULL, NULL, NULL, NULL, 'Fast-charging electric crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('tesla-model-3-2024', 'Tesla', 'Model 3', 2024, 'Saloon', 'Automatic', 'Electric', NULL, 325, NULL, 120, 5, 4, 578, NULL, NULL, NULL, NULL, 'Premium electric saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('tesla-model-y-2024', 'Tesla', 'Model Y', 2024, 'SUV', 'Automatic', 'Electric', NULL, 384, NULL, 125, 5, 5, 854, NULL, NULL, NULL, NULL, 'Performance electric SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('tesla-model-s-2024', 'Tesla', 'Model S', 2024, 'Saloon', 'Automatic', 'Electric', NULL, 518, NULL, 130, 5, 4, 901, NULL, NULL, NULL, NULL, 'Luxury performance sedan', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-polo-2024', 'Volkswagen', 'Polo', 2024, 'Hatchback', 'Manual', 'Petrol', 1498, 110, 130, 46, 5, 5, 351, NULL, NULL, NULL, NULL, 'German-built compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-golf-2024', 'Volkswagen', 'Golf', 2024, 'Hatchback', 'Manual', 'Petrol', 1498, 130, 140, 42, 5, 5, 381, NULL, NULL, NULL, NULL, 'Iconic family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-golf-2024', 'Volkswagen', 'Golf', 2024, 'Hatchback', 'Automatic', 'Hybrid', 1498, 204, 105, 55, 5, 5, 381, NULL, NULL, NULL, NULL, 'Efficient hybrid Golf', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-jetta-2024', 'Volkswagen', 'Jetta', 2024, 'Saloon', 'Automatic', 'Petrol', 1498, 130, 140, 42, 5, 4, 457, NULL, NULL, NULL, NULL, 'Compact executive saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-passat-2024', 'Volkswagen', 'Passat', 2024, 'Saloon', 'Automatic', 'Petrol', 1598, 150, 145, 41, 5, 4, 586, NULL, NULL, NULL, NULL, 'Executive family saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-tiguan-2024', 'Volkswagen', 'Tiguan', 2024, 'SUV', 'Manual', 'Petrol', 1498, 130, 140, 42, 5, 5, 520, NULL, NULL, NULL, NULL, 'Compact SUV with family focus', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-tiguan-2024', 'Volkswagen', 'Tiguan', 2024, 'SUV', 'Automatic', 'Hybrid', 1498, 204, 105, 55, 5, 5, 520, NULL, NULL, NULL, NULL, 'Efficient hybrid SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volkswagen-id3-2024', 'Volkswagen', 'ID.3', 2024, 'Hatchback', 'Automatic', 'Electric', NULL, 204, NULL, 110, 5, 5, 385, NULL, NULL, NULL, NULL, 'Practical electric hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('skoda-citigo-2024', 'Skoda', 'Citigo', 2024, 'Hatchback', 'Manual', 'Petrol', 1000, 75, 115, 52, 5, 5, 251, NULL, NULL, NULL, NULL, 'Budget city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('skoda-fabia-2024', 'Skoda', 'Fabia', 2024, 'Hatchback', 'Manual', 'Petrol', 1200, 110, 130, 46, 5, 5, 330, NULL, NULL, NULL, NULL, 'Value compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('skoda-octavia-2024', 'Skoda', 'Octavia', 2024, 'Hatchback', 'Manual', 'Petrol', 1500, 130, 140, 42, 5, 5, 380, NULL, NULL, NULL, NULL, 'Spacious family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('skoda-karoq-2024', 'Skoda', 'Karoq', 2024, 'SUV', 'Manual', 'Petrol', 1500, 150, 150, 39, 5, 5, 521, NULL, NULL, NULL, NULL, 'Czech-built compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('renault-clio-2024', 'Renault', 'Clio', 2024, 'Hatchback', 'Manual', 'Petrol', 1200, 100, 128, 46, 5, 5, 320, NULL, NULL, NULL, NULL, 'Stylish French city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('renault-megane-2024', 'Renault', 'Megane', 2024, 'Hatchback', 'Manual', 'Petrol', 1300, 130, 135, 44, 5, 5, 421, NULL, NULL, NULL, NULL, 'Practical family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('renault-scenic-2024', 'Renault', 'Scenic', 2024, 'MPV', 'Automatic', 'Petrol', 1600, 165, 150, 39, 7, 5, 627, NULL, NULL, NULL, NULL, 'Family 7-seater', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('renault-captur-2024', 'Renault', 'Captur', 2024, 'SUV', 'Manual', 'Petrol', 1200, 100, 130, 45, 5, 5, 422, NULL, NULL, NULL, NULL, 'Compact crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('renault-kadjar-2024', 'Renault', 'Kadjar', 2024, 'SUV', 'Manual', 'Petrol', 1600, 150, 150, 39, 5, 5, 528, NULL, NULL, NULL, NULL, 'Mid-size family SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('peugeot-108-2024', 'Peugeot', '108', 2024, 'Hatchback', 'Manual', 'Petrol', 1000, 72, 115, 52, 4, 3, 196, NULL, NULL, NULL, NULL, 'Budget French city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('peugeot-208-2024', 'Peugeot', '208', 2024, 'Hatchback', 'Manual', 'Petrol', 1200, 100, 128, 46, 5, 5, 311, NULL, NULL, NULL, NULL, 'Stylish compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('peugeot-308-2024', 'Peugeot', '308', 2024, 'Hatchback', 'Manual', 'Petrol', 1200, 130, 140, 42, 5, 5, 412, NULL, NULL, NULL, NULL, 'Family-friendly hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('peugeot-3008-2024', 'Peugeot', '3008', 2024, 'SUV', 'Manual', 'Petrol', 1200, 130, 140, 42, 5, 5, 520, NULL, NULL, NULL, NULL, 'Compact SUV with premium feel', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('peugeot-5008-2024', 'Peugeot', '5008', 2024, 'SUV', 'Automatic', 'Petrol', 1600, 180, 155, 38, 7, 5, 748, NULL, NULL, NULL, NULL, '7-seat family SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('citroen-c1-2024', 'Citroen', 'C1', 2024, 'Hatchback', 'Manual', 'Petrol', 1000, 72, 115, 52, 5, 5, 196, NULL, NULL, NULL, NULL, 'Budget city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('citroen-c3-2024', 'Citroen', 'C3', 2024, 'Hatchback', 'Manual', 'Petrol', 1200, 83, 120, 50, 5, 5, 310, NULL, NULL, NULL, NULL, 'Quirky compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('citroen-c5-aircross-2024', 'Citroen', 'C5 Aircross', 2024, 'SUV', 'Automatic', 'Petrol', 1600, 165, 150, 39, 5, 5, 720, NULL, NULL, NULL, NULL, 'Spacious mid-size SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mazda-mazda2-2024', 'Mazda', 'Mazda2', 2024, 'Hatchback', 'Manual', 'Petrol', 1498, 120, 135, 44, 5, 5, 280, NULL, NULL, NULL, NULL, 'Fun-to-drive compact car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mazda-mazda3-2024', 'Mazda', 'Mazda3', 2024, 'Hatchback', 'Manual', 'Petrol', 1998, 165, 155, 38, 5, 5, 322, NULL, NULL, NULL, NULL, 'Sporty family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mazda-cx-30-2024', 'Mazda', 'CX-30', 2024, 'SUV', 'Manual', 'Petrol', 1498, 121, 140, 42, 5, 5, 430, NULL, NULL, NULL, NULL, 'Compact crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mazda-cx-5-2024', 'Mazda', 'CX-5', 2024, 'SUV', 'Automatic', 'Petrol', 1998, 187, 165, 37, 5, 5, 620, NULL, NULL, NULL, NULL, 'Mid-size SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('honda-jazz-2024', 'Honda', 'Jazz', 2024, 'Hatchback', 'Automatic', 'Hybrid', 1498, 132, 125, 47, 5, 5, 298, NULL, NULL, NULL, NULL, 'Spacious hybrid hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('honda-civic-2024', 'Honda', 'Civic', 2024, 'Hatchback', 'Manual', 'Petrol', 1498, 131, 140, 42, 5, 5, 406, NULL, NULL, NULL, NULL, 'Dynamic family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('honda-cr-v-2024', 'Honda', 'CR-V', 2024, 'SUV', 'Automatic', 'Hybrid', 1998, 184, 130, 46, 5, 5, 617, NULL, NULL, NULL, NULL, 'Practical hybrid SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('toyota-yaris-2024', 'Toyota', 'Yaris', 2024, 'Hatchback', 'Automatic', 'Hybrid', 1490, 120, 115, 52, 5, 5, 286, NULL, NULL, NULL, NULL, 'Efficient hybrid city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('toyota-corolla-2024', 'Toyota', 'Corolla', 2024, 'Hatchback', 'Automatic', 'Hybrid', 1798, 122, 125, 47, 5, 5, 343, NULL, NULL, NULL, NULL, 'Reliable hybrid hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('toyota-rav4-2024', 'Toyota', 'RAV4', 2024, 'SUV', 'Automatic', 'Hybrid', 2487, 222, 135, 44, 5, 5, 580, NULL, NULL, NULL, NULL, 'Hybrid SUV with AWD', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('toyota-auris-2024', 'Toyota', 'Auris', 2024, 'Hatchback', 'Automatic', 'Hybrid', 1798, 122, 125, 47, 5, 5, 343, NULL, NULL, NULL, NULL, 'Hybrid estate car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('suzuki-alto-2024', 'Suzuki', 'Alto', 2024, 'Hatchback', 'Manual', 'Petrol', 658, 49, 110, 56, 4, 5, 168, NULL, NULL, NULL, NULL, 'Ultra-budget city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('suzuki-swift-2024', 'Suzuki', 'Swift', 2024, 'Hatchback', 'Manual', 'Petrol', 1197, 112, 130, 46, 5, 5, 268, NULL, NULL, NULL, NULL, 'Fun small hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('suzuki-vitara-2024', 'Suzuki', 'Vitara', 2024, 'SUV', 'Manual', 'Petrol', 1586, 140, 150, 39, 5, 5, 428, NULL, NULL, NULL, NULL, 'Compact SUV with attitude', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('seat-ibiza-2024', 'SEAT', 'Ibiza', 2024, 'Hatchback', 'Manual', 'Petrol', 1000, 110, 130, 46, 5, 5, 355, NULL, NULL, NULL, NULL, 'Spanish compact hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('seat-leon-2024', 'SEAT', 'Leon', 2024, 'Hatchback', 'Manual', 'Petrol', 1500, 150, 150, 39, 5, 5, 380, NULL, NULL, NULL, NULL, 'Sporty family hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('seat-ateca-2024', 'SEAT', 'Ateca', 2024, 'SUV', 'Manual', 'Petrol', 1500, 150, 150, 39, 5, 5, 510, NULL, NULL, NULL, NULL, 'Compact crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('lexus-ux-2024', 'Lexus', 'UX', 2024, 'SUV', 'Automatic', 'Hybrid', 1798, 184, 125, 47, 5, 5, 428, NULL, NULL, NULL, NULL, 'Luxury compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('lexus-nx-2024', 'Lexus', 'NX', 2024, 'SUV', 'Automatic', 'Hybrid', 2487, 242, 145, 41, 5, 5, 520, NULL, NULL, NULL, NULL, 'Luxury mid-size SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('lexus-rx-2024', 'Lexus', 'RX', 2024, 'SUV', 'Automatic', 'Hybrid', 3456, 308, 165, 36, 7, 5, 621, NULL, NULL, NULL, NULL, 'Luxury 7-seat SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mg-mg3-2024', 'MG', 'MG3', 2024, 'Hatchback', 'Manual', 'Petrol', 1497, 106, 130, 46, 5, 5, 293, NULL, NULL, NULL, NULL, 'Budget-friendly hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mg-zs-2024', 'MG', 'ZS', 2024, 'SUV', 'Manual', 'Petrol', 1497, 106, 130, 46, 5, 5, 405, NULL, NULL, NULL, NULL, 'Budget compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('mg-4-2024', 'MG', '4', 2024, 'Hatchback', 'Automatic', 'Electric', NULL, 204, NULL, 105, 5, 5, 350, NULL, NULL, NULL, NULL, 'Affordable electric hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('dacia-sandero-2024', 'Dacia', 'Sandero', 2024, 'Hatchback', 'Manual', 'Petrol', 1200, 75, 120, 50, 5, 5, 320, NULL, NULL, NULL, NULL, 'Ultra-budget no-frills hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('dacia-duster-2024', 'Dacia', 'Duster', 2024, 'SUV', 'Manual', 'Petrol', 1200, 100, 135, 44, 5, 5, 472, NULL, NULL, NULL, NULL, 'Rugged budget SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('jeep-wrangler-2024', 'Jeep', 'Wrangler', 2024, 'SUV', 'Automatic', 'Petrol', 2000, 284, 175, 34, 5, 2, 423, NULL, NULL, NULL, NULL, 'Iconic off-road SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('jeep-renegade-2024', 'Jeep', 'Renegade', 2024, 'SUV', 'Manual', 'Petrol', 1400, 120, 140, 42, 5, 5, 347, NULL, NULL, NULL, NULL, 'Compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('jeep-cherokee-2024', 'Jeep', 'Cherokee', 2024, 'SUV', 'Automatic', 'Petrol', 1995, 268, 165, 37, 5, 5, 547, NULL, NULL, NULL, NULL, 'Mid-size SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('fiat-500-2024', 'Fiat', '500', 2024, 'Hatchback', 'Manual', 'Petrol', 875, 63, 110, 56, 4, 2, 185, NULL, NULL, NULL, NULL, 'Iconic Italian city car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('fiat-500x-2024', 'Fiat', '500X', 2024, 'SUV', 'Manual', 'Petrol', 1400, 120, 140, 42, 5, 5, 359, NULL, NULL, NULL, NULL, 'Compact crossover', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('alfa-romeo-junior-2024', 'Alfa Romeo', 'Junior', 2024, 'Hatchback', 'Automatic', 'Petrol', 1200, 155, 145, 41, 5, 3, 240, NULL, NULL, NULL, NULL, 'Italian sporty hatchback', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('alfa-romeo-tonale-2024', 'Alfa Romeo', 'Tonale', 2024, 'SUV', 'Automatic', 'Petrol', 1600, 160, 150, 39, 5, 5, 540, NULL, NULL, NULL, NULL, 'Italian compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volvo-xc40-2024', 'Volvo', 'XC40', 2024, 'SUV', 'Automatic', 'Petrol', 1969, 197, 160, 37, 5, 5, 460, NULL, NULL, NULL, NULL, 'Scandinavian compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volvo-xc60-2024', 'Volvo', 'XC60', 2024, 'SUV', 'Automatic', 'Hybrid', 1969, 338, 125, 47, 5, 5, 570, NULL, NULL, NULL, NULL, 'Mid-size hybrid SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('volvo-s60-2024', 'Volvo', 'S60', 2024, 'Saloon', 'Automatic', 'Hybrid', 1969, 338, 125, 47, 5, 4, 483, NULL, NULL, NULL, NULL, 'Scandinavian hybrid saloon', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('porsche-macan-2024', 'Porsche', 'Macan', 2024, 'SUV', 'Automatic', 'Petrol', 1984, 252, 175, 34, 5, 5, 500, NULL, NULL, NULL, NULL, 'Sporty luxury compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('porsche-911-2024', 'Porsche', '911', 2024, 'Coupe', 'Automatic', 'Petrol', 3596, 382, 195, 32, 4, 2, 435, NULL, NULL, NULL, NULL, 'Legendary sports car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('range-rover-range-rover-evoque-2024', 'Range Rover', 'Range Rover Evoque', 2024, 'SUV', 'Automatic', 'Petrol', 1998, 250, 165, 37, 5, 5, 591, NULL, NULL, NULL, NULL, 'Luxury compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('range-rover-range-rover-sport-2024', 'Range Rover', 'Range Rover Sport', 2024, 'SUV', 'Automatic', 'Petrol', 3598, 355, 195, 32, 5, 5, 618, NULL, NULL, NULL, NULL, 'Luxury performance SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('range-rover-range-rover-2024', 'Range Rover', 'Range Rover', 2024, 'SUV', 'Automatic', 'Petrol', 3598, 400, 215, 30, 7, 5, 858, NULL, NULL, NULL, NULL, 'Full-size luxury SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('jaguar-f-type-2024', 'Jaguar', 'F-Type', 2024, 'Coupe', 'Automatic', 'Petrol', 2995, 380, 185, 33, 2, 2, 407, NULL, NULL, NULL, NULL, 'British sports car', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('jaguar-e-pace-2024', 'Jaguar', 'E-Pace', 2024, 'SUV', 'Automatic', 'Petrol', 2000, 296, 180, 33, 5, 5, 577, NULL, NULL, NULL, NULL, 'Luxury compact SUV', NULL, NULL);
INSERT INTO vehicles (slug, make, model, year, body_type, transmission, fuel_type, engine_size_cc, power_bhp, co2_g_km, mpg_combined, seating, doors, boot_litres, length_mm, width_mm, height_mm, gvwr_kg, description, image_url, manufacturer_url) VALUES ('jaguar-f-pace-2024', 'Jaguar', 'F-Pace', 2024, 'SUV', 'Automatic', 'Petrol', 2995, 296, 190, 32, 5, 5, 592, NULL, NULL, NULL, NULL, 'Luxury mid-size SUV', NULL, NULL);

-- Lenders
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('lease-loco', 'Lease Loco', 'https://www.leaseloco.com', '0333 300 0370', 'info@leaseloco.com', 'Personal lease deals', 'UK''s biggest car lease deal comparison site with offers from multiple lenders', NULL);
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('you-drive', 'You Drive', 'https://www.youdrive.com', '0203 744 3000', 'enquiries@youdrive.com', 'Personal car leasing', 'Award-winning personal car lease provider', NULL);
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('enterprise-rent-a-car', 'Enterprise Rent-A-Car', 'https://www.enterprise.co.uk', '0800 800 227', NULL, 'Car rental and lease', 'Long-term lease and short-term rental options', NULL);
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('leasingcom', 'Leasing.com', 'https://www.leasing.com', '01628 770055', 'hello@leasing.com', 'Vehicle leasing platform', 'Lease deals from multiple lenders on one platform', NULL);
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('cazoo', 'Cazoo', 'https://www.cazoo.co.uk', '0330 180 0046', NULL, 'Online car dealer with lease options', 'Buy or lease cars online with delivery options', NULL);
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('like-you-drive', 'Like You Drive', 'https://likeyoudrive.com', '0800 130 3636', NULL, 'Personal car leasing', 'Personal leasing contracts with flexible options', NULL);
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('vanarama', 'Vanarama', 'https://www.vanarama.com', '0330 111 0222', 'sales@vanarama.com', 'Van and car leasing', 'Wide range of vehicles for personal and business lease', NULL);
INSERT INTO lenders (slug, name, url, phone, email, specialization, description, logo_url) VALUES ('choosemycar', 'ChooseMyCar', 'https://www.choosemycar.com', '0800 043 8000', 'hello@choosemycar.com', 'Personal and business leasing', 'Flexible car lease contracts with comprehensive packages', NULL);

-- Lease Deals
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (2, 1, 239, 48, 10000, 1200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (2, 2, 249, 36, 12000, 1500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (2, 4, 255, 48, 10000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (4, 1, 299, 48, 10000, 1500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (4, 2, 319, 36, 12000, 1800, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (4, 4, 309, 48, 12000, 1600, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (4, 8, 329, 36, 15000, 2000, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (5, 4, 399, 48, 15000, 2200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (5, 6, 429, 36, 15000, 2500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (7, 1, 369, 48, 12000, 1800, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (7, 4, 389, 48, 15000, 2000, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (8, 2, 329, 48, 12000, 1600, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (12, 2, 249, 48, 10000, 1200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (12, 1, 239, 48, 10000, 1100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (14, 4, 299, 48, 12000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (14, 2, 319, 36, 12000, 1600, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (15, 4, 349, 48, 12000, 1700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (16, 7, 389, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (17, 4, 379, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (20, 4, 469, 48, 15000, 2400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (20, 8, 499, 36, 15000, 2700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (22, 4, 429, 48, 15000, 2100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (23, 8, 549, 48, 15000, 2700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (26, 4, 389, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (28, 4, 479, 48, 15000, 2400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (30, 8, 429, 48, 12000, 2100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (33, 4, 399, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (34, 4, 479, 48, 15000, 2400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (36, 8, 459, 48, 15000, 2300, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (37, 2, 219, 48, 10000, 1100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (39, 1, 349, 48, 12000, 1700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (39, 2, 369, 36, 15000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (40, 4, 329, 48, 12000, 1600, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (41, 7, 399, 48, 12000, 1800, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (42, 1, 199, 48, 10000, 1000, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (43, 2, 229, 48, 10000, 1100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (44, 4, 279, 48, 12000, 1300, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (45, 1, 329, 48, 12000, 1600, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (46, 7, 369, 48, 12000, 1700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (47, 2, 189, 48, 10000, 900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (48, 1, 219, 48, 10000, 1000, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (49, 4, 269, 48, 12000, 1300, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (50, 2, 319, 48, 12000, 1500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (51, 7, 449, 48, 15000, 2200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (52, 7, 529, 48, 15000, 2600, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (52, 8, 559, 36, 15000, 3000, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (53, 7, 649, 48, 15000, 3200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (55, 1, 269, 48, 10000, 1300, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (57, 2, 319, 48, 12000, 1500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (57, 4, 329, 36, 12000, 1700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (61, 1, 389, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (62, 7, 419, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (64, 2, 249, 48, 10000, 1200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (65, 4, 299, 48, 12000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (66, 1, 359, 48, 12000, 1700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (67, 2, 229, 48, 10000, 1100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (68, 1, 279, 48, 12000, 1300, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (70, 4, 319, 48, 12000, 1500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (73, 2, 239, 48, 10000, 1100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (74, 1, 289, 48, 12000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (75, 4, 349, 48, 12000, 1700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (78, 2, 219, 48, 10000, 1000, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (80, 1, 269, 48, 10000, 1300, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (82, 2, 329, 48, 12000, 1600, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (83, 4, 379, 48, 15000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (84, 2, 289, 48, 10000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (86, 1, 389, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (87, 4, 279, 48, 10000, 1300, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (88, 2, 299, 48, 12000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (89, 1, 429, 48, 15000, 2100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (92, 2, 229, 48, 10000, 1100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (93, 4, 319, 48, 12000, 1500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (94, 1, 249, 48, 10000, 1200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (95, 2, 299, 48, 12000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (97, 4, 399, 48, 12000, 1900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (98, 8, 499, 48, 15000, 2400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (100, 2, 199, 48, 10000, 900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (101, 1, 259, 48, 12000, 1200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (102, 7, 319, 48, 12000, 1500, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (103, 1, 179, 48, 10000, 800, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (104, 2, 249, 48, 12000, 1200, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (106, 4, 359, 48, 12000, 1700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (108, 2, 199, 48, 10000, 900, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (109, 1, 289, 48, 12000, 1400, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (112, 4, 429, 48, 15000, 2100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (113, 8, 549, 48, 15000, 2700, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (117, 4, 629, 48, 15000, 3100, NULL, NULL);
INSERT INTO lease_deals (vehicle_id, lender_id, monthly_price_gbp, term_months, annual_mileage, upfront_cost_gbp, description, source_url) VALUES (121, 8, 549, 48, 15000, 2700, NULL, NULL);

-- Vehicle Categories
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (1, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (1, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (2, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (2, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (3, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (4, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (4, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (5, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (5, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (5, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (6, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (6, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (7, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (7, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (7, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (8, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (8, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (8, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (10, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (10, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (10, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (11, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (11, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (12, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (12, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (12, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (13, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (14, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (15, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (15, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (16, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (16, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (16, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (17, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (18, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (19, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (19, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (19, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (20, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (20, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (20, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (20, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (21, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (21, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (21, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (22, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (22, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (22, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (23, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (23, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (23, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (24, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (24, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (24, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (25, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (25, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (25, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (25, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (26, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (27, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (27, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (27, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (28, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (28, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (28, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (28, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (29, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (29, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (29, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (30, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (30, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (30, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (31, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (31, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (31, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (32, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (32, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (33, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (34, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (34, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (34, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (35, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (35, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (35, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (36, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (36, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (36, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (37, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (37, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (38, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (38, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (39, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (39, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (39, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (40, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (40, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (41, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (41, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (42, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (42, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (43, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (43, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (44, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (45, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (45, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (46, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (46, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (46, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (47, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (47, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (48, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (48, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (49, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (50, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (50, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (51, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (52, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (52, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (52, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (53, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (53, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (53, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (54, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (54, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (54, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (55, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (57, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (58, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (58, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (59, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (59, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (60, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (60, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (61, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (61, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (61, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (62, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (62, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (63, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (64, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (64, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (65, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (66, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (66, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (67, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (67, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (68, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (70, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (70, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (71, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (71, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (72, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (73, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (73, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (74, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (74, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (75, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (75, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (76, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (76, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (77, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (78, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (78, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (79, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (79, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (80, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (82, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (82, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (83, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (83, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (84, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (84, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (86, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (86, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (86, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (87, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (87, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (88, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (88, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (89, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (89, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (89, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (90, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (91, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (92, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (92, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (93, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (93, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (94, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (94, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (95, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (96, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (96, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (97, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (97, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (97, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (97, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (98, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (98, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (98, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (98, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (99, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (99, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (99, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (99, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (100, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (101, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (101, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (101, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (102, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (102, 6);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (103, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (103, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (104, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (104, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (104, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (105, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (105, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (106, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (106, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (107, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (107, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (108, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (108, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (109, 1);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (109, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (109, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (110, 3);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (111, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (111, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (112, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (112, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (113, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (113, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (113, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (114, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (114, 5);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (114, 7);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (115, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (115, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (115, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (116, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (117, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (117, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (118, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (118, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (119, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (119, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (120, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (121, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (121, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (121, 8);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (122, 2);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (122, 4);
INSERT INTO vehicle_categories (vehicle_id, category_id) VALUES (122, 8);
